label: ErrorableCheckboxes
status: wip

context:
  componentSourcePath: './ErrorableCheckboxes.jsx'
  id: default
  errorMessage: 'Error message'
  label: 'Errorable Checkboxes'
  required: true
  title: 'ErrorableCheckboxes'
